Repository helm/chart-releaser-action, pull requests merged in 2025-01, with the labels that each got.

#220 update cr to v1.7.0
  .github/workflows/test-action.yml
  README.md
  action.yml
  cr.sh
Labels: size/M

#208 Adding support for ARM Runners
  action.yml
  cr.sh
Labels: size/S

#202 Write chart_version only if latest_tag is defined
  cr.sh
Labels: size/XS
